package typigen

type GeneratedModel struct {
	PackageName     string
	Imports         map[string]string
	Structs         []StructPogo
	AddConstructors []FunctionPogo
}

func (g GeneratedModel) String() string {
	var builder Builder
	builder.Printlnf("// Autogenerated by Typical-Go. DO NOT EDIT!!\n")
	builder.Printlnf("package %s", g.PackageName)

	for packageName := range g.Imports {
		builder.Printlnf(`import %s "%s"`, g.Imports[packageName], packageName)
	}

	for _, stru := range g.Structs {
		builder.Printlnf("%s", stru)
	}

	builder.Printlnf("func init() {")
	for _, funcPogo := range g.AddConstructors {
		builder.Printlnf("Context.AddConstructor(%s)", funcPogo)
	}
	builder.Printlnf("}")

	return builder.String()
}
