package gosrc

import (
	"reflect"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestInitializationModel(t *testing.T) {
	recipe := SourceRecipe{
		PackageName: "typical",
		Imports: []ImportPogo{
			{"", "fmt"},
			{"tgo", "github.com/typical-go/typical-go"},
		},
		Structs: []StructPogo{
			{
				Name: "Config",
				Fields: []reflect.StructField{
					{Name: "Name", Type: reflect.TypeOf("something")},
				},
			},
		},

		Constructors: []string{
			"contructor1",
		},
	}

	// fmt.Println(model.String())

	var builder strings.Builder
	recipe.Write(&builder)

	require.Equal(t, "// Autogenerated by Typical-Go. DO NOT EDIT\n\npackage typical\nimport  \"fmt\"\nimport tgo \"github.com/typical-go/typical-go\"\ntype Config struct{\nName string\n}\nfunc init() {\nContext.AddConstructor(contructor1)\n}\n",
		builder.String())
}

func TestBlank(t *testing.T) {
	testcase := []struct {
		recipe SourceRecipe
		blank  bool
	}{
		{recipe: SourceRecipe{}, blank: true},
		{recipe: SourceRecipe{Imports: []ImportPogo{ImportPogo{}}}, blank: false},
		{recipe: SourceRecipe{Structs: []StructPogo{StructPogo{}}}, blank: false},
		{recipe: SourceRecipe{Constructors: []string{""}}, blank: false},
		{recipe: SourceRecipe{MockTargets: []string{""}}, blank: false},
		{recipe: SourceRecipe{TestTargets: []string{""}}, blank: false},
	}

	for i, tt := range testcase {
		require.Equal(t, tt.blank, tt.recipe.Blank(), "%d: %+v", i, tt.recipe)
	}

}
