// Code generated by MockGen. DO NOT EDIT.
// Source: app/repository/music_repo.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	repository "github.com/typical-go/typical-rest-server/app/repository"
	reflect "reflect"
)

// MockMusicRepo is a mock of MusicRepo interface
type MockMusicRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMusicRepoMockRecorder
}

// MockMusicRepoMockRecorder is the mock recorder for MockMusicRepo
type MockMusicRepoMockRecorder struct {
	mock *MockMusicRepo
}

// NewMockMusicRepo creates a new mock instance
func NewMockMusicRepo(ctrl *gomock.Controller) *MockMusicRepo {
	mock := &MockMusicRepo{ctrl: ctrl}
	mock.recorder = &MockMusicRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMusicRepo) EXPECT() *MockMusicRepoMockRecorder {
	return m.recorder
}

// FindOne mocks base method
func (m *MockMusicRepo) FindOne(arg0 context.Context, arg1 int64) (*repository.Music, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", arg0, arg1)
	ret0, _ := ret[0].(*repository.Music)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne
func (mr *MockMusicRepoMockRecorder) FindOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockMusicRepo)(nil).FindOne), arg0, arg1)
}

// Find mocks base method
func (m *MockMusicRepo) Find(arg0 context.Context) ([]*repository.Music, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0)
	ret0, _ := ret[0].([]*repository.Music)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockMusicRepoMockRecorder) Find(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockMusicRepo)(nil).Find), arg0)
}

// Create mocks base method
func (m *MockMusicRepo) Create(arg0 context.Context, arg1 repository.Music) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockMusicRepoMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMusicRepo)(nil).Create), arg0, arg1)
}

// Delete mocks base method
func (m *MockMusicRepo) Delete(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockMusicRepoMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMusicRepo)(nil).Delete), arg0, arg1)
}

// Update mocks base method
func (m *MockMusicRepo) Update(arg0 context.Context, arg1 repository.Music) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockMusicRepoMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMusicRepo)(nil).Update), arg0, arg1)
}
