### Health Check

http://localhost:8089/application/health

### Pprof

http://localhost:8089/debug/pprof

### Goroutine

http://localhost:8089/debug/pprof/goroutine

### Vars

http://localhost:8089/debug/vars

