package generate

import (
	"os"
	"text/template"

	"github.com/typical-go/typical-go/appx"
	"github.com/typical-go/typical-rest-server/typical"
	"github.com/typical-go/typical-rest-server/typical/task/project"
)

const readmeTemplate = `<!-- Autogenerated by TypicalGo; Modify '_typical/generate/readme.go' to add more content -->
# {{ .Context.Name}}

{{ .Context.Description}}

## Configuration

{{ .ConfigDetail}}
`

var readmeModel = struct {
	Context      appx.Context
	ConfigDetail string
}{
	Context:      typical.Context,
	ConfigDetail: project.ConfigDetail(),
}

// Readme generate readme.md
func Readme() (err error) {

	t, err := template.New("readme").Parse(readmeTemplate)
	if err != nil {
		return
	}

	f, err := os.Create("README.md")
	if err != nil {
		return
	}

	err = t.Execute(f, readmeModel)
	if err != nil {
		return
	}
	return nil
}
