package generate

import (
	"os"
	"text/template"

	"github.com/typical-go/typical-rest-server/typical/task/project"
)

const readmeTemplate = `<!-- Autogenerated by TypicalGo; Modify '_typical/generate/readme.go' to add more content -->
# {{ .Ctx.Name}}

{{ .Ctx.Description}}

## Configuration

{{ .ConfigDetail}}
`

var readmeModel = struct {
	Ctx          project.Context
	ConfigDetail string
}{
	Ctx:          project.Ctx,
	ConfigDetail: project.ConfigDetail(),
}

// Readme generate readme.md
func Readme() (err error) {

	t, err := template.New("readme").Parse(readmeTemplate)
	if err != nil {
		return
	}

	f, err := os.Create("README.md")
	if err != nil {
		return
	}

	err = t.Execute(f, readmeModel)
	if err != nil {
		return
	}
	return nil
}
