#!/bin/bash

set -e

TYPTMP=.typical-tmp
TYPGO=$TYPTMP/bin/typical-go

if ! [ -s $TYPGO ]; then
	echo "Build typical-go"
	go build -o $TYPGO github.com/typical-go/typical-go
fi

$TYPGO run \
	-project-pkg="github.com/typical-go/typical-rest-server" \
	-typical-build="tools/typical-build" \
	-typical-tmp=$TYPTMP \
	$@
