#!/bin/bash
set -e

BIN=${TYPICAL_BIN:-bin}
CMD=${TYPICAL_CMD:-cmd}
BUILD_TOOL=${TYPICAL_BUILD_TOOL:-build-tool}
PRE_BUILDER=${TYPICAL_PRE_BUILDER:-pre-builder}

if ! [[ -f $BIN/$PRE_BUILDER ]]; then
    echo "Build the pre-build"
    go build -o $BIN/$PRE_BUILDER ./$CMD/$PRE_BUILDER
fi

./$BIN/$PRE_BUILDER
./$BIN/$BUILD_TOOL $@