#!/bin/bash
set -e

BIN=${TYPICAL_BIN:-bin}
CMD=${TYPICAL_CMD:-cmd}
BUILD_TOOL=${TYPICAL_BUILD_TOOL:-build-tool}
PRE_BUILDER=${TYPICAL_PRE_BUILDER:-pre-builder}

if ! [[ -f $BIN/$PRE_BUILDER ]]; then
    echo "Missing PreBuilder. Building Typical PreBuilder."
    go build -o $BIN/$PRE_BUILDER ./$CMD/$PRE_BUILDER    
fi

if ! [[ -z $(git status -s typical cmd/build-tool cmd/internal) ]]; then
    echo "Update detected. Building Typical BuildTool."
    go build -o $BIN/$BUILD_TOOL ./$CMD/$BUILD_TOOL
fi

./$BIN/$PRE_BUILDER
./$BIN/$BUILD_TOOL $@