// Autogenerated by Typical-Go. DO NOT EDIT.

package dependency

import (
	"github.com/typical-go/typical-rest-server/app/repository"
	"github.com/typical-go/typical-rest-server/app/service"
	"github.com/typical-go/typical-rest-server/typical"
)

func init() {
	typical.Context.AddConstructor(repository.NewBookRepo)
	typical.Context.AddConstructor(service.NewBookService)
	typical.Context.AddMockTarget("app/repository/book_repo.go")
	typical.Context.AddMockTarget("app/service/book_service.go")
}
