package typcfg_test

import (
	"io/ioutil"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/typical-go/typical-go/pkg/execkit"
	"github.com/typical-go/typical-go/pkg/typannot"
	"github.com/typical-go/typical-go/pkg/typgo"
	"github.com/typical-go/typical-rest-server/pkg/typcfg"
)

func TestCfgAnnotation_Annotate(t *testing.T) {
	os.MkdirAll("somepkg1", 0777)
	defer os.RemoveAll("somepkg1")

	unpatch := execkit.Patch([]*execkit.RunExpectation{})
	defer unpatch(t)

	var out strings.Builder
	typcfg.Stdout = &out
	defer func() { typcfg.Stdout = os.Stdout }()

	AppCfgAnnotation := &typcfg.AppCfgAnnotation{}
	c := &typannot.Context{
		Destination: "somepkg1",
		Context: &typgo.Context{
			BuildSys: &typgo.BuildSys{
				Descriptor: &typgo.Descriptor{ProjectName: "some-project"},
			},
		},
		Summary: &typannot.Summary{
			Annots: []*typannot.Annot{
				{
					TagName: "@app-cfg",
					Decl: &typannot.Decl{
						Name:    "SomeSample",
						Package: "mypkg",
						Type: &typannot.StructType{
							Fields: []*typannot.Field{
								{Name: "SomeField1", Type: "string", StructTag: `default:"some-text"`},
								{Name: "SomeField2", Type: "int", StructTag: `default:"9876"`},
							},
						},
					},
				},
			},
		},
	}

	require.NoError(t, AppCfgAnnotation.Annotate(c))

	b, _ := ioutil.ReadFile("somepkg1/app_cfg_annotated.go")
	require.Equal(t, `package somepkg1

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/kelseyhightower/envconfig"
)

func init() { 
	typapp.AppendCtor(
		&typapp.Constructor{Name: "",Fn: LoadSomeSample},
	)
}

// LoadSomeSample load env to new instance of SomeSample
func LoadSomeSample() (*mypkg.SomeSample, error) {
	var cfg mypkg.SomeSample
	if err := envconfig.Process("SOMESAMPLE", &cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}
`, string(b))

	require.Equal(t, "Generate @app-cfg to somepkg1/app_cfg_annotated.go\n", out.String())

}

func TestCfgAnnotation_Annotate_DotEnvTRUE(t *testing.T) {
	unpatch := execkit.Patch([]*execkit.RunExpectation{})
	defer unpatch(t)

	var out strings.Builder
	typcfg.Stdout = &out
	defer func() { typcfg.Stdout = os.Stdout }()

	defer os.Clearenv()
	defer os.Remove("some-target")
	defer os.Remove(".env")

	AppCfgAnnotation := &typcfg.AppCfgAnnotation{
		Target:   "some-target",
		Template: "some-template",
		DotEnv:   true,
	}
	c := &typannot.Context{
		Context: &typgo.Context{
			BuildSys: &typgo.BuildSys{
				Descriptor: &typgo.Descriptor{ProjectName: "some-project"},
			},
		},
		Summary: &typannot.Summary{Annots: []*typannot.Annot{
			{
				TagName:  "@app-cfg",
				TagParam: `ctor_name:"ctor1" prefix:"SS"`,
				Decl: &typannot.Decl{
					Name:    "SomeSample",
					Package: "mypkg",
					Type: &typannot.StructType{
						Fields: []*typannot.Field{
							{Name: "SomeField1", Type: "string", StructTag: `default:"some-text"`},
							{Name: "SomeField2", Type: "int", StructTag: `default:"9876"`},
						},
					},
				},
			},
		}},
	}

	require.NoError(t, AppCfgAnnotation.Annotate(c))

	b, _ := ioutil.ReadFile("some-target")
	require.Equal(t, `some-template`, string(b))

	b, _ = ioutil.ReadFile(".env")
	require.Equal(t, "SS_SOMEFIELD1=some-text\nSS_SOMEFIELD2=9876\n", string(b))
	require.Equal(t, "some-text", os.Getenv("SS_SOMEFIELD1"))
	require.Equal(t, "9876", os.Getenv("SS_SOMEFIELD2"))

	require.Equal(t, "Generate @app-cfg to some-target\nUPDATE_ENV: +SS_SOMEFIELD1 +SS_SOMEFIELD2\n", out.String())
}

func TestCfgAnnotation_Annotate_Predefined(t *testing.T) {
	target := "cfg-target"

	unpatch := execkit.Patch([]*execkit.RunExpectation{})
	defer unpatch(t)
	defer os.RemoveAll(target)

	appCfgAnnotation := &typcfg.AppCfgAnnotation{
		TagName:  "@some-tag",
		Template: "some-template",
		Target:   target,
	}
	c := &typannot.Context{
		Context: &typgo.Context{
			BuildSys: &typgo.BuildSys{
				Descriptor: &typgo.Descriptor{ProjectName: "some-project"},
			},
		},
		Summary: &typannot.Summary{
			Annots: []*typannot.Annot{
				{
					TagName: "@some-tag",
					Decl: &typannot.Decl{
						Name:    "SomeSample",
						Package: "mypkg",
						Type:    &typannot.StructType{Fields: []*typannot.Field{}},
					},
				},
			},
		},
	}

	require.NoError(t, appCfgAnnotation.Annotate(c))

	b, _ := ioutil.ReadFile(target)

	require.Equal(t, `some-template`, string(b))

}

func TestCfgAnnotation_Annotate_RemoveTargetWhenNoAnnotation(t *testing.T) {
	target := "target1"
	defer os.Remove(target)
	ioutil.WriteFile(target, []byte("some-content"), 0777)
	c := &typannot.Context{
		Context: &typgo.Context{},
		Summary: &typannot.Summary{},
	}

	AppCfgAnnotation := &typcfg.AppCfgAnnotation{Target: target}
	require.NoError(t, AppCfgAnnotation.Annotate(c))
	_, err := os.Stat(target)
	require.True(t, os.IsNotExist(err))
}

func TestCreateAndLoadDotEnv_EnvFileExist(t *testing.T) {
	target := "some-env"
	ioutil.WriteFile(target, []byte("key1=val111\nkey2=val222"), 0777)
	var out strings.Builder
	typcfg.Stdout = &out
	defer os.Remove(target)
	defer func() { typcfg.Stdout = os.Stdout }()

	typcfg.CreateAndLoadDotEnv(target, []*typcfg.AppCfg{
		{
			Fields: []*typcfg.Field{
				{Key: "key1", Default: "val1"},
				{Key: "key2", Default: "val2"},
				{Key: "key3", Default: "val3"},
			},
		},
	})

	b, _ := ioutil.ReadFile(target)
	require.Equal(t, "key1=val111\nkey2=val222\nkey3=val3\n", string(b))
	require.Equal(t, "UPDATE_ENV: +key3\n", out.String())
}
