package typcfg

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/typical-go/typical-go/pkg/common"
	"github.com/typical-go/typical-go/pkg/typannot"
	"github.com/typical-go/typical-go/pkg/typgo"
)

type (
	// AppCfgAnnotation handle @app-cfg annotation
	// e.g. `@app-cfg (prefix: "PREFIX" ctor_name:"CTOR")`
	AppCfgAnnotation struct {
		TagName  string // By default is `@app-cfg`
		Template string // By default defined in defaultCfgTemplate variable
		Target   string // By default is `cmd/PROJECT_NAME/cfg_annotated.go`
		DotEnv   string // Dotenv path. It will be generated if not empty
		UsageDoc string // Usage documentation path. It will be if not emtpy
	}
	// AppCfgTmplData template
	AppCfgTmplData struct {
		Package string
		Imports []string
		Configs []*AppCfg
	}
)

// Stdout standard output
var Stdout io.Writer = os.Stdout

const defaultCfgTemplate = `package {{.Package}}

// Autogenerated by Typical-Go. DO NOT EDIT.

import ({{range $import := .Imports}}
	"{{$import}}"{{end}}
)

func init() { {{if .Configs}}
	typapp.AppendCtor({{range $c := .Configs}}
		&typapp.Constructor{Name: "{{$c.CtorName}}",Fn: Load{{$c.Name}}},{{end}}
	){{end}}
}
{{range $c := .Configs}}
// Load{{$c.Name}} load env to new instance of {{$c.Name}}
func Load{{$c.Name}}() (*{{$c.SpecType}}, error) {
	var cfg {{$c.SpecType}}
	if err := envconfig.Process("{{$c.Prefix}}", &cfg); err != nil {
		return nil, err
	}
	return &cfg, nil
}{{end}}
`

//
// AppCfgAnnotation
//

var _ typannot.Annotator = (*AppCfgAnnotation)(nil)

// Annotate AppCfg to prepare dependency-injection and env-file
func (m *AppCfgAnnotation) Annotate(c *typannot.Context) error {
	context := CreateContext(c, m.getTagName())

	if err := m.generate(context); err != nil {
		return err
	}

	if m.DotEnv != "" {
		if err := GenerateAndLoadDotEnv(m.DotEnv, context); err != nil {
			return err
		}
	}

	if m.UsageDoc != "" {
		if err := GenerateUsage(m.UsageDoc, context); err != nil {
			return err
		}
	}

	return nil
}

func (m *AppCfgAnnotation) generate(c *Context) error {
	target := m.getTarget(c)
	if len(c.Configs) < 1 {
		os.Remove(target)
		return nil
	}

	fmt.Fprintf(Stdout, "Generate @app-cfg to %s\n", target)
	if err := common.ExecuteTmplToFile(target, m.getTemplate(), &AppCfgTmplData{
		Package: filepath.Base(c.Destination),
		Imports: c.CreateImports(typgo.ProjectPkg, "github.com/kelseyhightower/envconfig"),
		Configs: c.Configs,
	}); err != nil {
		return err
	}
	typgo.GoImports(target)
	return nil
}

func (m *AppCfgAnnotation) getTagName() string {
	if m.TagName == "" {
		m.TagName = "@app-cfg"
	}
	return m.TagName
}

func (m *AppCfgAnnotation) getTemplate() string {
	if m.Template == "" {
		m.Template = defaultCfgTemplate
	}
	return m.Template
}

func (m *AppCfgAnnotation) getTarget(c *Context) string {
	if m.Target == "" {
		m.Target = fmt.Sprintf("%s/app_cfg_annotated.go", c.Destination)
	}
	return m.Target
}
