package typcfg_test

import (
	"fmt"
	"io/ioutil"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/typical-go/typical-rest-server/pkg/typcfg"
)

func TestGenerateUsage(t *testing.T) {
	var out strings.Builder
	typcfg.Stdout = &out
	defer func() { typcfg.Stdout = os.Stdout }()

	target := "sample.md"
	c := &typcfg.Context{
		Configs: []*typcfg.AppCfg{
			{
				Fields: []*typcfg.Field{
					{Key: "APP_NAME", Default: "some-name", Required: true},
					{Key: "APP_DEBUG", Default: "false", Required: false},
				},
			},
			{
				Fields: []*typcfg.Field{
					{Key: "DB_HOST", Default: "some-host", Required: false},
					{Key: "DB_PORT", Default: "some-port", Required: true},
				},
			},
		},
	}
	err := typcfg.GenerateUsage(target, c)
	require.NoError(t, err)
	defer os.Remove(target)

	b, _ := ioutil.ReadFile(target)
	expected := fmt.Sprintf(`# Usage

<!-- Autogenerated by Typical-Go. DO NOT EDIT. 

Command to generate:
	./typicalw annotate

Annotation Tag:
	@app-cfg

Annotation Help:
	https://pkg.go.dev/github.com/typical-go/typical-rest-server/pkg/typcfg
-->

## Configuration List
| Field Name | Default | Required | 
|---|---|:---:|
| APP_NAME | some-name | Yes |
| APP_DEBUG | false |  |
| DB_HOST | some-host |  |
| DB_PORT | some-port | Yes |

## DotEnv example
%s

`, "```\nAPP_NAME=some-name\nAPP_DEBUG=false\nDB_HOST=some-host\nDB_PORT=some-port\n```")
	require.Equal(t, expected, string(b))

	require.Equal(t, "Generate 'sample.md'\n", out.String())
}
