package typical

import (
	"github.com/typical-go/typical-rest-server/app"
	"github.com/typical-go/typical-rest-server/typical/appctx"
	"github.com/typical-go/typical-rest-server/typical/infra/ipostgres"
)

// Context instance of Context
var Context appctx.Context

const readmeTemplate = `<!-- Autogenerated by Typical-Go; Modify 'typical/readme_template.go' to add more content -->
# {{ .Name}}

{{ .Description}}

## Configuration

{{ .ConfigDoc }}

`

func init() {
	// TODO: consider to use toml file
	Context = appctx.Context{
		Name:           "Typical-RESTful-Server",
		Version:        "0.1.0",
		ConfigPrefix:   "APP",
		Description:    "Example of typical and scalable RESTful API Server for Go",
		Container:      container(),
		ReadmeTemplate: readmeTemplate,
		Modules: []interface{}{
			&app.Config{},
			&ipostgres.PGConfig{},
		},
	}
}
