// Autogenerated by Typical-Go. DO NOT EDIT.

package typical

import (
	"github.com/kelseyhightower/envconfig"
	"github.com/typical-go/typical-rest-server/app/config"
	"github.com/typical-go/typical-rest-server/app/repository"
	"github.com/typical-go/typical-rest-server/app/service"
	"github.com/typical-go/typical-rest-server/pkg/module/typpostgres"
	"github.com/typical-go/typical-rest-server/pkg/module/typserver"
)

type Config struct {
	App    *config.Config
	Server *typserver.Config
	Pg     *typpostgres.Config
}

func init() {
	Context.AddConstructor(func() (*Config, error) {
		var cfg Config
		err := envconfig.Process("", &cfg)
		return &cfg, err
	})
	Context.AddConstructor(func(cfg *Config) *config.Config {
		return cfg.App
	})
	Context.AddConstructor(func(cfg *Config) *typpostgres.Config {
		return cfg.Pg
	})
	Context.AddConstructor(func(cfg *Config) *typserver.Config {
		return cfg.Server
	})
	Context.AddConstructor(repository.NewBookRepository)
	Context.AddConstructor(service.NewBookService)
	Context.AddMockTarget("app/repository/book_repo.go")
	Context.AddMockTarget("app/service/book_service.go")
	Context.AddTestTarget("./app")
	Context.AddTestTarget("./app/config")
	Context.AddTestTarget("./app/controller")
	Context.AddTestTarget("./app/repository")
	Context.AddTestTarget("./app/service")
}
