package typical

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/pkg/typapp"
	"github.com/typical-go/typical-go/pkg/typdep"
	"github.com/typical-go/typical-rest-server/restserver/repository"
	"github.com/typical-go/typical-rest-server/restserver/service"
)

func init() {
	typapp.AppendConstructor(
		typdep.NewConstructor(repository.NewBookRepo),
		typdep.NewConstructor(service.NewBookService),
	)
}
