package typical

const readmeTemplate = `<!-- Autogenerated by Typical-Go; Modify 'typical/readme_template.go' to add more content -->
# {{ .Name}}

{{ .Description}}

## Configuration
{{ .ConfigDoc }}
`
