package dependency

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-rest-server/app/repository"
	"github.com/typical-go/typical-rest-server/app/service"
	"github.com/typical-go/typical-rest-server/typical"
)

func init() {
	typical.Context.Constructors.Append(repository.NewBookRepo)
	typical.Context.Constructors.Append(service.NewBookService)
}
