package dependency

import "github.com/typical-go/typical-rest-server/app/repository"
import "github.com/typical-go/typical-rest-server/app/service"
import "github.com/typical-go/typical-rest-server/typical"

func init() {
	// Autogenerated by Typical-Go. DO NOT EDIT.
	typical.Context.Constructors.Append(repository.NewBookRepo)
	typical.Context.Constructors.Append(service.NewBookService)
}
