// Autogenerated by Typical-Go. DO NOT EDIT.

package dependency

import "github.com/typical-go/typical-rest-server/typical"

func init() {
	typical.Context.TestTargets.Add("./app")
	typical.Context.TestTargets.Add("./app/config")
	typical.Context.TestTargets.Add("./app/controller")
	typical.Context.TestTargets.Add("./app/repository")
	typical.Context.TestTargets.Add("./app/service")
}
