// Autogenerated by Typical-Go. DO NOT EDIT

package main

import _ "github.com/golang-migrate/migrate/database/postgres"
import _ "github.com/golang-migrate/migrate/source/file"
import _ "github.com/lib/pq"

func init() {
}
