package readme

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestReadmeRecipe(t *testing.T) {

	recipe := &Readme{
		Title:       "some-title",
		Description: "some-descrption",
	}
	recipe.SetSection("section-title1", Section{Content: "some-content"})
	recipe.SetSection("section-title2", Section{Content: "{{.Field1}}", Data: struct{ Field1 string }{"some-field1"}})
	recipe.SetSection("section-title1", Section{Content: "revision-content"})

	var builder strings.Builder
	recipe.Write(&builder)

	require.Equal(t, `<!-- Autogenerated by Typical-Go. DO NOT EDIT. -->

# some-title

some-descrption

## section-title1

revision-content

## section-title2

some-field1

`, builder.String())
}
