package readme

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestReadmeRecipe(t *testing.T) {

	recipe := Recipe{
		Title:       "some-title",
		Description: "some-descrption",
		Sections: []Section{
			{Title: "section-title1", Content: "section-content"},
			{Title: "section-title1", Content: "{{.Field1}}", Data: struct{ Field1 string }{"some-field1"}},
		},
	}

	var builder strings.Builder
	recipe.Write(&builder)

	require.Equal(t, `<!-- Autogenerated by Typical-Go. DO NOT EDIT. -->

# some-title

some-descrption

## section-title1

section-content

## section-title1

some-field1

`, builder.String())
}
