// Autogenerated by Typical-Go. DO NOT EDIT.

package main

import "github.com/typical-go/typical-rest-server/typical"

func init() {
	typical.Context.AddTestTarget("./app")
	typical.Context.AddTestTarget("./app/config")
	typical.Context.AddTestTarget("./app/controller")
	typical.Context.AddTestTarget("./app/repository")
	typical.Context.AddTestTarget("./app/service")
}
