package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-rest-server/app/repository"
	"github.com/typical-go/typical-rest-server/app/service"
	"github.com/typical-go/typical-rest-server/typical"
)

func init() {
	typical.Descriptor.AppendConstructor(
		repository.NewBookRepo,
		repository.NewMusicRepo,
		service.NewBookService,
		service.NewMusicService,
	)
}
