package buildtool

import (
	"io"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/kelseyhightower/envconfig"
	"github.com/typical-go/typical-rest-server/EXPERIMENTAL/typicmd/buildtool/markdown"
	"github.com/typical-go/typical-rest-server/EXPERIMENTAL/typictx"
)

const (
	configTemplate = `| Key | Type | Default | Required | Description |	
|---|---|---|---|---|{{range .}}
|{{usage_key .}}|{{usage_type .}}|{{usage_default .}}|{{usage_required .}}|{{usage_description .}}|{{end}}`
)

// Readme detail
type Readme struct {
	*typictx.Context
	Title       string
	Description string
}

// Markdown to return the markdown
func (r *Readme) Markdown(w io.Writer) *markdown.Markdown {
	md := &markdown.Markdown{Writer: w}
	md.Comment("Autogenerated by Typical-Go. DO NOT EDIT.")
	md.Heading1(r.Title)
	md.Writeln(r.Description)
	r.gettingStarted(md)
	r.configuration(md)
	r.releaseDistribution(md)
	return md
}

func (r *Readme) gettingStarted(md *markdown.Markdown) {
	md.Heading2("Getting Started")
	md.Heading3("Prerequisite")
	md.OrderedList(
		"Install [Go](https://golang.org/doc/install) or `brew install go`",
	)
	md.Heading3("Run")
	md.Writeln("Use `./typicalw run` to compile and run local development. You can find the binary at `bin` folder")
}

func (r *Readme) releaseDistribution(md *markdown.Markdown) (err error) {
	md.Heading2("Release Distribution")
	md.Writeln("Use `./typicalw release` to make the release. You can find the binary at `release` folder. More information check [here](https://typical-go.github.io/release.html)")
	return
}

func (r *Readme) configuration(md *markdown.Markdown) {
	md.Heading2("Configuration")
	for _, module := range r.Modules {
		name := strcase.ToCamel(module.Name)
		if name != "" {
			md.Heading3(name)
		}
		var builder strings.Builder
		envconfig.Usagef(module.Prefix, module.Spec, &builder, configTemplate)
		md.Writeln(builder.String())
	}
}
